### ISSUE TITLE
How to get a CKB address through RPC interface?

### ISSUE THREAD

**Issue by ahonn** [ckb-js/nexus#238]
It seems that the CKB address is not displayed in the extension, and no method for returning the address was found in the provided RPC interface.

**Comment by ahonn** [comment]
Thanks, And it would be even better if encodeToAddress or method like `wallet_getAddress` could be built-in.

**Comment by homura** [comment]
> Thanks, And it would be even better if encodeToAddress or method like `wallet_getAddress` could be built-in.

Address is indeed easier to understand with, but the address is relative, the mainnet address is different from other networks, so to keep return of `getXLocks` be correct, lock may be a better choice. Even more, we recommend to de-emphasize the concept of the address in dApp and use nickname instead, because in the UTxO model, addresses can easily change over time
